project_id = "atinyqtgnyjeonylydll"

[functions.manage-api-key]
verify_jwt = true

[functions.chat]
verify_jwt = false

[functions.widget]
verify_jwt = false

[functions.process-document]
verify_jwt = true

[functions.admin]
verify_jwt = false
